baseurl = "http://vampirecoffee.net/"
languageCode = "en-us"
title = "The Internet Of Skye"
footnotereturnlinkcontents = "↩"
canonifyurls = true

[params]
    description = "Thoughts on the Internet (and how it's broken), sci-fi/fantasy (and how it's broken), computer science (and how it's broken), and cats (and how they're fluffy)."
    author = "Skye"
